dist: xenial
language: cpp
sudo: enabled

install:
  - .ci/script/run-install.sh

before_script:
  - .ci/script/run-cppcheck.sh -out=xml

script:
  - .ci/script/run-build-libspectre.sh config/at90can32-default.cmake
  - .ci/script/run-build-libspectre.sh config/at90can64-default.cmake
  - .ci/script/run-build-libspectre.sh config/at90can128-default.cmake
  - .ci/script/run-build-libspectre.sh config/atmega640-default.cmake
  - .ci/script/run-build-libspectre.sh config/atmega1280-default.cmake
  - .ci/script/run-build-libspectre.sh config/atmega1284-default.cmake
  - .ci/script/run-build-libspectre.sh config/atmega2560-default.cmake
  - .ci/script/run-build-libspectre.sh config/atmega328p-default.cmake
  - .ci/script/run-build-libspectre.sh config/atmega16u4-default.cmake
  - .ci/script/run-build-libspectre.sh config/atmega32u4-default.cmake
  - .ci/script/run-build-all-examples.sh
  - .ci/script/run-pre-test-prepare-coverage-report.sh
  - .ci/script/run-build-libspectre.sh config/host-default.cmake
  - .ci/script/run-test.sh
  - .ci/script/run-post-test-create-coverage-report.sh

after_script:
  - .ci/script/run-cleanup.sh
