dist: xenial
language: cpp
sudo: enabled

install:
  - .ci/script/run-install.sh

before_script:
  - .ci/script/run-cppcheck.sh -out=xml
  - .ci/script/run-codespell.sh ${TRAVIS_BUILD_DIR}

script:
  - .ci/script/run-build-libsnowfox-all.sh
  - .ci/script/run-build-example-all.sh
  - .ci/script/run-pre-test-prepare-coverage-report.sh
  - .ci/script/run-build-libsnowfox.sh config/host-default.cmake
  - .ci/script/run-test.sh
  - .ci/script/run-post-test-create-coverage-report.sh
